#!/bin/bash

PUSH_SWAP="../push_swap/push_swap"
CHECKER=./checker_Mac

function run_tests()
{
	local TESTS=$1
	local NUMBERS=$2
	local INT_MIN=-1000000
	local INT_MAX=1000000

	printf "Test (%3d elems):\n" "$NUMBERS"
	for ((i=1; i<=TESTS; i++)); do
		args=$(seq $INT_MIN $INT_MAX | gshuf | head -n $NUMBERS | tr '\n' ' ')
		output=$($PUSH_SWAP $args)
		moves=$(echo "$output" | wc -l)
		if (( $NUMBERS == 100 )); then
			if (( $moves < 700)); then
				printf "\e[32m[ 100%% ]\e[0m "
			elif (( $moves < 1100 )); then
				printf "\e[34m[ 80%% ]\e[0m "
			elif (( $moves < 1300 )); then
				printf "\e[33m[ 60%% ]\e[0m "
			else
				printf "\e[31m[ 0%% ]\e[0m "
			fi
		elif (( $NUMBERS == 500 )); then
			if (( $moves < 5500)); then
				printf "\e[32m[ 100%% ]\e[0m "
			elif (( $moves < 8500 )); then
				printf "\e[34m[ 80%% ]\e[0m "
			elif (( $moves < 11500 )); then
				printf "\e[33m[ 60%% ]\e[0m "
			else
				printf "\e[31m[ 0%% ]\e[0m "
			fi
		fi
	done
	echo
}

run_tests 10 100
run_tests 10 500
